"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, ExternalLink, PackageCheck, Plus, Printer, Save, Search, Ship, WalletCards } from "lucide-react";
import type { Inquiry, SalesOrder } from "@/lib/types";
const stages=["待确认","待收定金","生产中","待验货","待收尾款","待发货","运输中","已签收","已完成","暂停"];
const closed=["已签收","已完成","暂停"];
export default function OrderManager({initialOrders,customers}:{initialOrders:SalesOrder[];customers:Inquiry[]}){
 const [orders,setOrders]=useState(initialOrders),[adding,setAdding]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("全部"),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState({customerId:"",customer:"",productSummary:"",currency:"USD",amount:0,paid:0,incoterm:"FOB",paymentTerm:"30% deposit, 70% before shipment",destination:""});
 const today=new Date().toISOString().slice(0,10);
 const filtered=useMemo(()=>orders.filter(o=>(filter==="全部"||o.stage===filter)&&[o.orderNo,o.customer,o.productSummary,o.destination,o.trackingNo].join(" ").toLowerCase().includes(search.toLowerCase())),[orders,filter,search]);
 const update=(id:string,key:keyof SalesOrder,value:unknown)=>setOrders(items=>items.map(item=>item.id===id?{...item,[key]:value}:item));
 function chooseCustomer(id:string){const customer=customers.find(x=>x.id===id);setDraft({...draft,customerId:id,customer:customer?.company||customer?.name||customer?.email||"",productSummary:customer?.product||"",destination:customer?.country||"",currency:customer?.dealCurrency||"USD",amount:Number(customer?.dealValue)||0});}
 async function create(){const response=await fetch("/api/admin/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});if(!response.ok){setNotice("请先选择或填写客户");return;}const {order}=await response.json();setOrders(items=>[order,...items]);setAdding(false);setNotice("订单已创建");}
 async function save(order:SalesOrder){const response=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(order)});setNotice(response.ok?"订单进度已保存":"保存失败，请重试");}
 const outstanding=orders.filter(o=>!closed.includes(o.stage)).reduce((sum,o)=>sum+(o.currency==="USD"?Math.max(0,o.amount-o.paid):0),0);
 const delayed=orders.filter(o=>!closed.includes(o.stage)&&((o.shippingDue&&o.shippingDue<today)||(o.productionDue&&o.productionDue<today))).length;
 return <div className="orders-admin"><header><div><small>ORDER FULFILLMENT</small><h1>订单履约</h1><p>成交后集中管理收款、生产、验货、发货和运输信息，避免漏收尾款或错过交期。</p></div><div><button className="print-order" onClick={()=>window.print()}><Printer/> 打印</button><button onClick={()=>setAdding(!adding)}><Plus/> 新建订单</button></div></header>
 <div className="order-metrics"><article><PackageCheck/><span>订单总数</span><b>{orders.length}</b></article><article><WalletCards/><span>未收余额（USD）</span><b>{outstanding.toLocaleString()}</b></article><article className={delayed?"danger":""}><AlertTriangle/><span>可能延期</span><b>{delayed}</b></article><article><Ship/><span>运输中</span><b>{orders.filter(o=>o.stage==="运输中").length}</b></article></div>
 {adding&&<section className="order-create"><h2>从客户创建订单</h2><div className="admin-grid"><label>选择 CRM 客户<select value={draft.customerId} onChange={e=>chooseCustomer(e.target.value)}><option value="">手动填写</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company||c.name||c.email}</option>)}</select></label><label>客户 / 公司<input value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})}/></label><label>产品与数量<input value={draft.productSummary} onChange={e=>setDraft({...draft,productSummary:e.target.value})}/></label><label>目的地<input value={draft.destination} onChange={e=>setDraft({...draft,destination:e.target.value})}/></label><label>订单金额<div className="money-input"><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option>USD</option><option>EUR</option><option>GBP</option><option>CNY</option></select><input type="number" min="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></div></label><label>已收款<input type="number" min="0" value={draft.paid} onChange={e=>setDraft({...draft,paid:Number(e.target.value)})}/></label><label>贸易条款<select value={draft.incoterm} onChange={e=>setDraft({...draft,incoterm:e.target.value})}>{["EXW","FOB","CIF","DAP","DDP"].map(x=><option key={x}>{x}</option>)}</select></label><label>付款条款<input value={draft.paymentTerm} onChange={e=>setDraft({...draft,paymentTerm:e.target.value})}/></label></div><button onClick={create}><Save/> 创建订单</button></section>}
 <div className="order-toolbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索订单号、客户、产品、目的地或物流单号"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>全部</option>{stages.map(x=><option key={x}>{x}</option>)}</select><span>{filtered.length} 个订单</span></div><p className="crm-notice">{notice}</p>
 <div className="order-list">{filtered.map(order=>{const balance=Math.max(0,order.amount-order.paid);const late=!closed.includes(order.stage)&&Boolean((order.shippingDue&&order.shippingDue<today)||(order.productionDue&&order.productionDue<today));return <article key={order.id} className={late?"late":""}><div className="order-head"><div><small>{order.orderNo}</small><b>{order.customer}</b><span>{order.productSummary||"尚未填写产品"}</span></div><select value={order.stage} onChange={e=>update(order.id,"stage",e.target.value)}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>{late&&<div className="order-alert"><AlertTriangle/> 计划日期已经超过，请联系供应商或货代确认并更新进度。</div>}<div className="order-finance"><div><span>订单金额</span><b>{order.currency} {order.amount.toLocaleString()}</b></div><div><span>已收款</span><b>{order.currency} {order.paid.toLocaleString()}</b></div><div className={balance?"unpaid":"paid"}><span>未收余额</span><b>{order.currency} {balance.toLocaleString()}</b></div><div><span>收款进度</span><b>{order.amount?Math.min(100,order.paid/order.amount*100).toFixed(0):0}%</b></div></div><div className="order-fields"><label>订单金额<input type="number" min="0" value={order.amount} onChange={e=>update(order.id,"amount",Number(e.target.value))}/></label><label>累计已收<input type="number" min="0" value={order.paid} onChange={e=>update(order.id,"paid",Number(e.target.value))}/></label><label>贸易条款<select value={order.incoterm} onChange={e=>update(order.id,"incoterm",e.target.value)}>{["EXW","FOB","CIF","DAP","DDP"].map(x=><option key={x}>{x}</option>)}</select></label><label>目的地<input value={order.destination} onChange={e=>update(order.id,"destination",e.target.value)}/></label><label>生产完成日期<input type="date" value={order.productionDue||""} onChange={e=>update(order.id,"productionDue",e.target.value)}/></label><label>计划发货日期<input type="date" value={order.shippingDue||""} onChange={e=>update(order.id,"shippingDue",e.target.value)}/></label><label>货代 / 承运商<input value={order.forwarder||""} onChange={e=>update(order.id,"forwarder",e.target.value)}/></label><label>物流单号 / 提单号<input value={order.trackingNo||""} onChange={e=>update(order.id,"trackingNo",e.target.value)}/></label><label className="wide">付款条款<input value={order.paymentTerm} onChange={e=>update(order.id,"paymentTerm",e.target.value)}/></label><label className="wide">订单备注<textarea value={order.notes||""} onChange={e=>update(order.id,"notes",e.target.value)} placeholder="包装确认、验货要求、异常情况和处理记录……"/></label></div><div className="order-actions">{order.trackingNo&&<a href={`https://www.google.com/search?q=${encodeURIComponent(order.trackingNo)}`} target="_blank" rel="noreferrer"><ExternalLink/> 查询物流单号</a>}<button onClick={()=>save(order)}><Save/> 保存订单</button></div></article>})}</div></div>;
}
