"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, BarChart3, Calculator, ClipboardList, Copy, FileText, ImageUp, Inbox, LogIn, LogOut, Package, Plus, Save, Settings, Star, Trash2, Users } from "lucide-react";
import type { Inquiry, Product, SalesOrder, SiteSettings } from "@/lib/types";
import type { EventRecord } from "@/lib/operations";
import Operations from "./operations";
import ProductManager from "./product-manager";
import type { DeploymentReadiness } from "./operations";
import BrandingDetails from "./branding-details";
import TrustDetails from "./trust-details";
import { LogisticsManager, QuoteManager } from "./trade-tools";
import CRM from "./crm";
import OrderManager from "./orders";

export default function AdminPanel({ initialAuthed, initialProducts, inquiries, initialOrders, initialSettings, events = [], readiness }: { initialAuthed:boolean; initialProducts:Product[]; inquiries:Inquiry[]; initialOrders:SalesOrder[]; initialSettings:SiteSettings; events?:EventRecord[]; readiness:DeploymentReadiness }) {
  const [products,setProducts]=useState(initialProducts), [settings,setSettings]=useState(initialSettings), [password,setPassword]=useState(""), [error,setError]=useState(""), [saved,setSaved]=useState(false), [uploading,setUploading]=useState(""), [productSearch,setProductSearch]=useState(""), [tab,setTab]=useState<"operations"|"products"|"inquiries"|"crm"|"quotes"|"orders"|"logistics"|"settings">("operations");
  useEffect(()=>{const brand=document.querySelector(".admin-brand");const mark=brand?.querySelector("span");const name=brand?.querySelector("b");if(name)name.textContent=settings.companyName.toUpperCase();if(mark){mark.textContent="";if(settings.logo){const image=document.createElement("img");image.src=settings.logo;image.alt=`${settings.companyName} logo`;mark.appendChild(image);}else mark.textContent=settings.companyName.split(/\s+/).map(word=>word[0]).join("").slice(0,2).toUpperCase()||"FN";}},[settings.companyName,settings.logo]);
  async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(r.ok)location.reload();else setError("密码不正确，请重新输入");}
  async function logout(){await fetch("/api/admin/logout",{method:"POST"});location.reload();}
  async function saveProducts(next=products){try {const r=await fetch("/api/admin/products",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(!r.ok) throw new Error();setSaved(true);setTimeout(()=>setSaved(false),2200);}catch {alert("保存失败，请检查登录状态并重试");}}
  async function saveSettings(){try {const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});if(!r.ok) throw new Error();setSaved(true);setTimeout(()=>setSaved(false),2200);}catch {alert("保存失败，请检查登录状态并重试");}}
  function update(i:number,key:keyof Product,value:Product[keyof Product]){setProducts(p=>p.map((x,n)=>n===i?{...x,[key]:value}:x));}
  function move(i:number,direction:-1|1){const target=i+direction;if(target<0||target>=products.length)return;setProducts(items=>{const next=[...items];[next[i],next[target]]=[next[target],next[i]];return next;});}
  function duplicate(i:number){const source=products[i];const copy={...source,id:`${source.id}-copy-${Date.now().toString().slice(-5)}`,name:`${source.name} Copy`,active:false,featured:false};setProducts(items=>[...items.slice(0,i+1),copy,...items.slice(i+1)]);}
  const completeness=(product:Product)=>Math.round([product.image,product.name,product.category,product.description,product.material,product.moq,product.blade,product.size,product.applications,product.features,product.customization,product.leadTime].filter(Boolean).length/12*100);
  async function upload(i:number,file?:File){if(!file)return;setUploading(products[i].id);const fd=new FormData();fd.append("image",file);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});if(r.ok){const {url}=await r.json();const next=products.map((p,n)=>n===i?{...p,image:url,imagePosition:undefined}:p);setProducts(next);await saveProducts(next);}else alert("图片上传失败，请使用 JPG、PNG 或 WebP，且不超过 5MB");setUploading("");}
  if(!initialAuthed)return <main className="admin-login"><a href="/"><ArrowLeft/> 返回网站</a><form onSubmit={login}><div className="admin-mark">FN</div><span>剪刀与切割工具网站后台</span><h1>欢迎回来</h1><p>请输入后台管理密码</p><label>管理密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus placeholder="请输入密码"/></label>{error&&<div className="admin-error">{error}</div>}<button><LogIn/> 进入后台</button><small>请在 Render 环境变量中设置强密码<br/>不要使用默认密码 admin123</small></form></main>;
  return <main className="admin"><aside><div className="admin-brand"><span>FN</span><b>FORGENOVA</b><small>管理后台</small></div><button className={tab==="operations"?"active":""} onClick={()=>setTab("operations")}><BarChart3/> 运营管理</button><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}><Package/> 产品管理</button><button className={tab==="inquiries"?"active":""} onClick={()=>setTab("inquiries")}><Inbox/> 客户询盘 <i>{inquiries.length}</i></button><button className={tab==="crm"?"active":""} onClick={()=>setTab("crm")}><Users/> 客户管理</button><button className={tab==="quotes"?"active":""} onClick={()=>setTab("quotes")}><FileText/> 报价单</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}><ClipboardList/> 订单履约</button><button className={tab==="logistics"?"active":""} onClick={()=>setTab("logistics")}><Calculator/> 物流测算</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Settings/> 网站设置</button><div className="admin-side-actions"><a href="/"><ArrowLeft/> 查看网站</a><button onClick={logout}><LogOut/> 退出登录</button></div></aside><section className="admin-main">
  {tab==="operations" && <Operations events={events} inquiries={inquiries} products={products} settings={settings} readiness={readiness}/>}
  {tab==="quotes" && <QuoteManager inquiries={inquiries} products={products} settings={settings}/>}
  {tab==="logistics" && <LogisticsManager/>}
  {tab==="crm" && <CRM initialCustomers={inquiries}/>}
  {tab==="orders" && <OrderManager initialOrders={initialOrders} customers={inquiries}/>}
  {tab==="products" && <ProductManager initialProducts={products}/>}
  {tab==="inquiries"&&inquiries.some(item=>item.attachmentUrl)&&<section className="inquiry-attachments"><h2>客户参考附件</h2>{inquiries.filter(item=>item.attachmentUrl).map(item=><a key={item.id} href={item.attachmentUrl} target="_blank"><b>{item.attachmentName||"查看附件"}</b><span>{item.name||item.email} · {item.product||"未指定产品"}</span></a>)}</section>}
  {tab==="products"&&<><header><div><small>PRODUCT MANAGEMENT</small><h1>剪刀产品与独立详情页</h1><p>这里的资料会同步显示在首页和产品详情页。</p></div><div><button className="add" onClick={()=>setProducts([...products,{id:crypto.randomUUID(),name:"New Scissor Product",category:"Scissors",material:"",price:"Request quote",moq:"",status:"Request Quote",description:"",blade:"",size:"",applications:"",features:"",customization:"",leadTime:""}])}><Plus/> 添加产品</button><button className="save" onClick={()=>saveProducts()}><Save/> {saved?"已保存":"保存修改"}</button></div></header><div className="admin-products">{products.map((p,i)=><article key={p.id}><div className="admin-card-head"><b>产品 {String(i+1).padStart(2,"0")} · {p.name}</b><button aria-label="删除" onClick={()=>setProducts(products.filter((_,n)=>n!==i))}><Trash2/></button></div><div className="product-upload"><div className="image-preview">{p.image?<img src={p.image} alt="产品预览"/>:<ImageUp/>}</div><label className="upload-button"><ImageUp/> {uploading===p.id?"上传中...":"上传/更换真实产品图"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading===p.id} onChange={e=>upload(i,e.target.files?.[0])}/></label><small>建议 1200×1200 以上，JPG/PNG/WebP，最大 5MB</small></div><div className="admin-grid"><label>产品英文名称<input value={p.name} onChange={e=>update(i,"name",e.target.value)}/></label><label>分类<input value={p.category} onChange={e=>update(i,"category",e.target.value)}/></label><label>价格 / 询价显示<input value={p.price} onChange={e=>update(i,"price",e.target.value)}/></label><label>最小起订量<input value={p.moq} onChange={e=>update(i,"moq",e.target.value)}/></label><label>主体材质<input value={p.material} onChange={e=>update(i,"material",e.target.value)}/></label><label>状态<select value={p.status} onChange={e=>update(i,"status",e.target.value)}><option>In Stock</option><option>Made to Order</option><option>Request Quote</option></select></label><label>刀刃 / 刃口<input value={p.blade||""} onChange={e=>update(i,"blade",e.target.value)}/></label><label>尺寸<input value={p.size||""} onChange={e=>update(i,"size",e.target.value)}/></label><label>交期<input value={p.leadTime||""} onChange={e=>update(i,"leadTime",e.target.value)}/></label><label className="wide">英文介绍<textarea value={p.description} onChange={e=>update(i,"description",e.target.value)}/></label><label className="wide">适用客户/场景（英文）<textarea value={p.applications||""} onChange={e=>update(i,"applications",e.target.value)}/></label><label className="wide">卖点（英文，用 | 分隔）<textarea value={p.features||""} onChange={e=>update(i,"features",e.target.value)} placeholder="Sharp blade|Comfort grip|Retail-ready packaging"/></label><label className="wide">OEM 可定制内容（英文）<textarea value={p.customization||""} onChange={e=>update(i,"customization",e.target.value)}/></label></div></article>)}</div></>}
  {tab==="inquiries"&&<><header><div><small>INQUIRY CENTER</small><h1>客户询盘</h1><p>这里只保留客户提交的原始需求；跟进状态和客户资料请到“客户管理”。</p></div></header><div className="inquiries">{inquiries.length===0?<div className="empty"><Inbox/><h3>暂时还没有询盘</h3><p>客户提交询价后会显示在这里。</p></div>:inquiries.map(q=><article key={q.id}><div><b>{q.name||"未填写姓名"}</b><span>{new Date(q.createdAt).toLocaleString("zh-CN")}</span></div><p>{q.message}</p><dl><div><dt>需求类型</dt><dd>{q.requestType||"Wholesale quote"}</dd></div><div><dt>邮箱</dt><dd><a href={`mailto:${q.email}`}>{q.email}</a></dd></div><div><dt>公司 / 国家</dt><dd>{q.company||"—"} · {q.country||"—"}</dd></div><div><dt>产品 / 数量</dt><dd>{q.product||"—"} · {q.quantity||"—"}</dd></div></dl></article>)}</div></>}
  {tab==="settings"&&<><header><div><small>WEBSITE SETTINGS</small><h1>品牌、联系与社媒账号</h1><p>保存后首页会立即同步更新。</p></div><div><button className="save" onClick={saveSettings}><Save/> {saved?"已保存":"保存设置"}</button></div></header><div className="settings-card"><div className="admin-grid"><label>公司/品牌英文名称<input value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})}/></label><label>首页英文标题<input value={settings.tagline||""} onChange={e=>setSettings({...settings,tagline:e.target.value})}/></label><label>联系邮箱<input type="email" value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label>WhatsApp 完整链接<input value={settings.whatsapp} onChange={e=>setSettings({...settings,whatsapp:e.target.value})} placeholder="https://wa.me/8613800000000"/></label><label>微信号<input value={settings.wechat} onChange={e=>setSettings({...settings,wechat:e.target.value})}/></label><label>Instagram 主页链接<input value={settings.instagram||""} onChange={e=>setSettings({...settings,instagram:e.target.value})} placeholder="https://instagram.com/..."/></label><label>Facebook 主页链接<input value={settings.facebook||""} onChange={e=>setSettings({...settings,facebook:e.target.value})} placeholder="https://facebook.com/..."/></label><label>TikTok 主页链接<input value={settings.tiktok||""} onChange={e=>setSettings({...settings,tiktok:e.target.value})} placeholder="https://tiktok.com/@..."/></label><label className="wide">首页公司介绍（英文）<textarea value={settings.about} onChange={e=>setSettings({...settings,about:e.target.value})}/></label></div></div></>}
  {tab==="settings"&&<div className="settings-card tracking-settings"><h2>广告与访问统计</h2><p>留空不会加载对应平台。填写后自动记录页面浏览，并在客户提交询盘时发送转化事件。</p><div className="admin-grid"><label>Google Analytics 衡量 ID<input value={settings.googleAnalyticsId||""} onChange={e=>setSettings({...settings,googleAnalyticsId:e.target.value.trim()})} placeholder="G-XXXXXXXXXX"/></label><label>Meta Pixel ID<input value={settings.metaPixelId||""} onChange={e=>setSettings({...settings,metaPixelId:e.target.value.trim()})} placeholder="纯数字 Pixel ID"/></label><label>TikTok Pixel ID<input value={settings.tiktokPixelId||""} onChange={e=>setSettings({...settings,tiktokPixelId:e.target.value.trim()})} placeholder="例如 CXXXXXXXXXXXX"/></label></div></div>}
  {tab==="settings"&&<BrandingDetails settings={settings} setSettings={setSettings}/>}
  {tab==="settings"&&<TrustDetails settings={settings} setSettings={setSettings}/>}
  </section></main>;
}
