"use client";
import { useState } from "react";
import { ArrowLeft, Inbox, LogIn, Package, Plus, Save, Trash2 } from "lucide-react";
import type { Inquiry, Product } from "@/lib/types";
export default function AdminPanel({ initialAuthed, initialProducts, inquiries }: { initialAuthed: boolean; initialProducts: Product[]; inquiries: Inquiry[] }) {
  const [authed, setAuthed] = useState(initialAuthed), [products, setProducts] = useState(initialProducts), [password, setPassword] = useState(""), [error, setError] = useState(""), [saved, setSaved] = useState(false), [tab, setTab] = useState<"products"|"inquiries">("products");
  async function login(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/admin/login", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({password}) }); if (r.ok) location.reload(); else setError("密码不正确，请重新输入"); }
  async function save() { const r = await fetch("/api/admin/products", { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify(products) }); if (r.ok) { setSaved(true); setTimeout(() => setSaved(false), 2200); } }
  function update(i:number, key:keyof Product, value:string) { setProducts(p => p.map((x,n) => n === i ? {...x,[key]:value} : x)); }
  if (!authed) return <main className="admin-login"><a href="/"><ArrowLeft/> 返回网站</a><form onSubmit={login}><div className="admin-mark">FN</div><span>FORGENOVA 管理后台</span><h1>欢迎回来</h1><p>请输入后台管理密码</p><label>管理密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus placeholder="请输入密码"/></label>{error && <div className="admin-error">{error}</div>}<button><LogIn/> 进入后台</button><small>首次部署默认密码：admin123<br/>上线前请在 Render 环境变量中修改</small></form></main>;
  return <main className="admin"><aside><div className="admin-brand"><span>FN</span><b>FORGENOVA</b><small>管理后台</small></div><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}><Package/> 产品管理</button><button className={tab==="inquiries"?"active":""} onClick={()=>setTab("inquiries")}><Inbox/> 客户询盘 <i>{inquiries.length}</i></button><a href="/"><ArrowLeft/> 查看网站</a></aside><section className="admin-main">{tab === "products" ? <><header><div><small>PRODUCT MANAGEMENT</small><h1>产品与价格</h1><p>修改后点击保存，前台会立即更新。</p></div><div><button className="add" onClick={()=>setProducts([...products,{id:crypto.randomUUID(),name:"New Product",category:"Fasteners",material:"",price:"Request quote",moq:"",status:"Request Quote",description:""}])}><Plus/> 添加产品</button><button className="save" onClick={save}><Save/> {saved?"已保存":"保存修改"}</button></div></header><div className="admin-products">{products.map((p,i)=><article key={p.id}><div className="admin-card-head"><b>产品 {String(i+1).padStart(2,"0")}</b><button aria-label="删除" onClick={()=>setProducts(products.filter((_,n)=>n!==i))}><Trash2/></button></div><div className="admin-grid"><label>产品名称<input value={p.name} onChange={e=>update(i,"name",e.target.value)}/></label><label>分类<input value={p.category} onChange={e=>update(i,"category",e.target.value)}/></label><label>价格 / 询价显示<input value={p.price} onChange={e=>update(i,"price",e.target.value)}/></label><label>最小起订量<input value={p.moq} onChange={e=>update(i,"moq",e.target.value)}/></label><label>材质<input value={p.material} onChange={e=>update(i,"material",e.target.value)}/></label><label>状态<select value={p.status} onChange={e=>update(i,"status",e.target.value)}><option>In Stock</option><option>Made to Order</option><option>Request Quote</option></select></label><label className="wide">英文介绍<textarea value={p.description} onChange={e=>update(i,"description",e.target.value)}/></label></div></article>)}</div></> : <><header><div><small>INQUIRY CENTER</small><h1>客户询盘</h1><p>网站访客提交的询价信息。</p></div></header><div className="inquiries">{inquiries.length===0?<div className="empty"><Inbox/><h3>暂时还没有询盘</h3><p>客户提交询价后会显示在这里。</p></div>:inquiries.map(q=><article key={q.id}><div><b>{q.name || "未填写姓名"}</b><span>{new Date(q.createdAt).toLocaleString("zh-CN")}</span></div><p>{q.message}</p><dl><div><dt>邮箱</dt><dd><a href={`mailto:${q.email}`}>{q.email}</a></dd></div><div><dt>公司</dt><dd>{q.company||"—"}</dd></div><div><dt>国家</dt><dd>{q.country||"—"}</dd></div><div><dt>产品 / 数量</dt><dd>{q.product||"—"} · {q.quantity||"—"}</dd></div></dl></article>)}</div></>}</section></main>;
}
