"use client";

import { ArrowDown, ArrowUp, Copy, Download, Eye, FileUp, ImageUp, Plus, Save, Star, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Product } from "@/lib/types";

export default function ProductManager({ initialProducts }: { initialProducts: Product[] }) {
  const [products, setProducts] = useState(initialProducts);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [uploading, setUploading] = useState("");
  const [message, setMessage] = useState("");
  const baseline = useRef(JSON.stringify(initialProducts));
  const dirty = JSON.stringify(products) !== baseline.current;
  const visible = useMemo(() => products.map((product, index) => ({ product, index })).filter(({ product }) => {
    const matchesSearch = `${product.name} ${product.category} ${product.sku || ""}`.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = status === "all" || (status === "live" ? product.active !== false : product.active === false);
    return matchesSearch && matchesStatus;
  }), [products, search, status]);

  function update<K extends keyof Product>(index: number, key: K, value: Product[K]) { setProducts(items => items.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= products.length) return; setProducts(items => { const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  function duplicate(index: number) { const source = products[index]; const copy = { ...source, id: `${source.id}-copy-${Date.now().toString().slice(-5)}`, name: `${source.name} Copy`, active: false, featured: false }; setProducts(items => [...items.slice(0, index + 1), copy, ...items.slice(index + 1)]); }
  function completeness(product: Product) { return Math.round([product.image, product.name, product.category, product.description, product.material, product.moq, product.model, product.size, product.applications, product.features, product.customization, product.leadTime].filter(Boolean).length / 12 * 100); }
  async function save(next = products) { try { const response = await fetch("/api/admin/products", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); if (!response.ok) throw new Error(); baseline.current = JSON.stringify(next); setMessage("产品资料已保存"); } catch { setMessage("保存失败，请检查登录状态并重试"); } }
  async function upload(index: number, file?: File) { if (!file) return; setUploading(products[index].id); const data = new FormData(); data.append("image", file); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); if (response.ok) { const { url } = await response.json(); const next = products.map((product, i) => i === index ? { ...product, image: url, imagePosition: undefined } : product); setProducts(next); await save(next); } else setMessage("图片上传失败，请使用不超过 5MB 的 JPG、PNG 或 WebP"); setUploading(""); }
  async function uploadGallery(index: number, files: FileList | null) { if (!files?.length) return; const selected = Array.from(files).slice(0, Math.max(0, 6 - (products[index].images?.length || 0))); setUploading(`${products[index].id}-gallery`); const urls: string[] = []; for (const file of selected) { const data = new FormData(); data.append("image", file); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); if (response.ok) urls.push((await response.json()).url); } const next = products.map((product, i) => i === index ? { ...product, images: [...(product.images || []), ...urls].slice(0, 6) } : product); setProducts(next); if (urls.length) await save(next); else setMessage("细节图上传失败，请检查图片格式和大小"); setUploading(""); }
  function add() { setProducts(items => [...items, { id: `product-${Date.now()}`, name: "New Hardware Product", category: "Hardware", material: "", price: "Request quote", moq: "", status: "Request Quote", description: "", active: false, featured: false }]); }

  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [dirty]);

  const csvFields: (keyof Product)[] = ["id", "sku", "name", "category", "model", "material", "size", "blade", "price", "moq", "status", "packaging", "certification", "leadTime", "description", "applications", "features", "customization", "specifications", "image", "active", "featured"];
  const escapeCsv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
  function exportCsv() { const content = `\uFEFF${[csvFields.join(","), ...products.map(product => csvFields.map(field => escapeCsv(product[field])).join(","))].join("\r\n")}`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); link.download = `products-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = [], value = "", quoted = false; for (let i = 0; i < text.length; i++) { const character = text[i]; if (quoted && character === '"' && text[i + 1] === '"') { value += '"'; i++; } else if (character === '"') quoted = !quoted; else if (character === "," && !quoted) { row.push(value); value = ""; } else if ((character === "\n" || character === "\r") && !quoted) { if (character === "\r" && text[i + 1] === "\n") i++; row.push(value); if (row.some(Boolean)) rows.push(row); row = []; value = ""; } else value += character; } row.push(value); if (row.some(Boolean)) rows.push(row); return rows; }
  async function importCsv(file?: File) { if (!file) return; const rows = parseCsv((await file.text()).replace(/^\uFEFF/, "")); const headers = rows.shift()?.map(value => value.trim()) || []; if (!headers.includes("name") || !headers.includes("category")) return setMessage("导入失败：CSV 必须包含 name 和 category 列"); const imported = rows.map((row, index) => { const values = Object.fromEntries(headers.map((header, i) => [header, row[i] || ""])); return { ...values, id: values.id || `product-${Date.now()}-${index}`, name: values.name, category: values.category, material: values.material || "", price: values.price || "Request quote", moq: values.moq || "", status: (["In Stock", "Made to Order", "Request Quote"].includes(values.status) ? values.status : "Request Quote") as Product["status"], description: values.description || "", active: values.active === "true", featured: values.featured === "true" } as Product; }).filter(product => product.name); if (!imported.length) return setMessage("没有找到可导入的产品"); if (!confirm(`将用 CSV 中的 ${imported.length} 个产品替换当前产品列表，确定继续吗？`)) return; setProducts(imported); setMessage("CSV 已读取，请检查后点击“保存全部”才会正式生效"); }

  return <div className="product-manager">
    <header><div><small>PRODUCT MANAGEMENT</small><h1>剪刀与五金产品库</h1><p>支持剪刀、手工具、园林工具、紧固件及其他五金；新产品完成资料后再上架。</p></div><div><a className="backup-download" href="/api/admin/backup"><Download /> 全站备份</a><button className="add" onClick={exportCsv}><Download /> 产品 CSV</button><label className="product-import"><FileUp /> 导入 CSV<input type="file" accept=".csv,text/csv" onChange={event => importCsv(event.target.files?.[0])} /></label><button className="add" onClick={add}><Plus /> 添加产品</button><button className="save" onClick={() => save()}><Save /> {dirty ? "保存全部 *" : "已保存"}</button></div></header>
    <div className="product-tools"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索产品名称、分类或 SKU" /><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">全部产品</option><option value="live">已上架</option><option value="draft">已下架</option></select><span>共 {products.length} 个 · 上架 {products.filter(product => product.active !== false).length} 个</span></div>
    {message && <p className="admin-notice" role="status">{message}</p>}
    <div className="admin-products">{visible.map(({ product: p, index: i }) => <article key={p.id}>
      <div className="admin-card-head"><div><b>产品 {String(i + 1).padStart(2, "0")} · {p.name}</b><span className={`publish-badge ${p.active === false ? "draft" : "live"}`}>{p.active === false ? "已下架" : "已上架"}</span><small>资料完整度 {completeness(p)}%</small></div><div className="product-card-actions"><button title="上移" disabled={i === 0} onClick={() => move(i, -1)}><ArrowUp /></button><button title="下移" disabled={i === products.length - 1} onClick={() => move(i, 1)}><ArrowDown /></button><button title="复制" onClick={() => duplicate(i)}><Copy /></button><button title="删除" onClick={() => confirm(`确定删除 ${p.name}？`) && setProducts(items => items.filter((_, n) => n !== i))}><Trash2 /></button></div></div>
      <div className="product-publish-controls"><label><input type="checkbox" checked={p.active !== false} onChange={event => update(i, "active", event.target.checked)} /> 在前台展示</label><label><input type="checkbox" checked={Boolean(p.featured)} onChange={event => update(i, "featured", event.target.checked)} /><Star /> 首页优先推荐</label>{p.active !== false && <a href={`/products/${p.id}`} target="_blank"><Eye /> 预览详情页</a>}</div>
      <div className="product-upload"><div className="image-preview">{p.image ? <img src={p.image} alt="产品预览" /> : <ImageUp />}</div><label className="upload-button"><ImageUp /> {uploading === p.id ? "上传中..." : "上传/更换主图"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={Boolean(uploading)} onChange={event => upload(i, event.target.files?.[0])} /></label><label className="upload-button secondary"><ImageUp /> {uploading === `${p.id}-gallery` ? "上传中..." : "添加细节图"}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={Boolean(uploading)} onChange={event => uploadGallery(i, event.target.files)} /></label><small>主图 + 最多 6 张细节图，单张最大 5MB</small></div>{Boolean(p.images?.length)&&<div className="gallery-manager">{p.images!.map((image,index)=><div key={`${image}-${index}`}><img src={image} alt={`细节图 ${index+1}`}/><button onClick={()=>update(i,"images",p.images!.filter((_,n)=>n!==index))}>移除</button></div>)}</div>}
      <div className="admin-grid"><label>产品英文名称<input value={p.name} onChange={event => update(i, "name", event.target.value)} /></label><label>产品编号 / SKU<input value={p.sku || ""} onChange={event => update(i, "sku", event.target.value)} /></label><label>产品分类<input value={p.category} onChange={event => update(i, "category", event.target.value)} placeholder="Hand Tools / Fasteners / Garden Tools" /></label><label>型号 / Model<input value={p.model || ""} onChange={event => update(i, "model", event.target.value)} /></label><label>价格 / 询价显示<input value={p.price} onChange={event => update(i, "price", event.target.value)} /></label><label>最小起订量<input value={p.moq} onChange={event => update(i, "moq", event.target.value)} /></label><label>主体材质<input value={p.material} onChange={event => update(i, "material", event.target.value)} /></label><label>销售状态<select value={p.status} onChange={event => update(i, "status", event.target.value as Product["status"])}><option>In Stock</option><option>Made to Order</option><option>Request Quote</option></select></label><label>刀刃 / 表面处理 / 工艺<input value={p.blade || ""} onChange={event => update(i, "blade", event.target.value)} /></label><label>尺寸 / 规格<input value={p.size || ""} onChange={event => update(i, "size", event.target.value)} /></label><label>包装方式<input value={p.packaging || ""} onChange={event => update(i, "packaging", event.target.value)} placeholder="Carton, blister card, color box..." /></label><label>认证 / 标准<input value={p.certification || ""} onChange={event => update(i, "certification", event.target.value)} placeholder="CE, RoHS, DIN, ANSI..." /></label><label>交期<input value={p.leadTime || ""} onChange={event => update(i, "leadTime", event.target.value)} /></label><label className="wide">英文介绍<textarea value={p.description} onChange={event => update(i, "description", event.target.value)} /></label><label className="wide">其他规格参数（英文，每行一项，格式 Name: Value）<textarea value={p.specifications || ""} onChange={event => update(i, "specifications", event.target.value)} placeholder={'Weight: 350 g\nFinish: Zinc plated\nHardness: HRC 52–56'} /></label><label className="wide">适用客户/场景（英文）<textarea value={p.applications || ""} onChange={event => update(i, "applications", event.target.value)} /></label><label className="wide">卖点（英文，用 | 分隔）<textarea value={p.features || ""} onChange={event => update(i, "features", event.target.value)} placeholder="Durable construction|Comfort grip|Retail-ready packaging" /></label><label className="wide">OEM 可定制内容（英文）<textarea value={p.customization || ""} onChange={event => update(i, "customization", event.target.value)} /></label></div>
    </article>)}</div>
  </div>;
}
