"use client";

import { ImageUp, Trash2 } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { SiteSettings } from "@/lib/types";

export default function TrustDetails({ settings, setSettings }: { settings: SiteSettings; setSettings: Dispatch<SetStateAction<SiteSettings>> }) {
  async function upload(files: FileList | null) { if (!files?.length) return; const remaining = Math.max(0, 6 - (settings.companyImages?.length || 0)); const urls: string[] = []; for (const file of Array.from(files).slice(0, remaining)) { const data = new FormData(); data.append("image", file); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); if (response.ok) urls.push((await response.json()).url); } if (urls.length) setSettings(value => ({ ...value, companyImages: [...(value.companyImages || []), ...urls].slice(0, 6) })); else alert("图片上传失败，请使用不超过 5MB 的 JPG、PNG 或 WebP"); }
  return <div className="settings-card trust-details"><h2>公司实力与贸易信息</h2><p>填写真实信息后，前台会自动生成“Manufacturing & Quality”信任模块；空白内容不会显示。</p><div className="company-image-editor"><label className="upload-button"><ImageUp /> 上传工厂 / 团队 / 质检照片<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files)} /></label><small>最多 6 张，建议横版 1600×1000px，使用真实照片。</small></div>{Boolean(settings.companyImages?.length)&&<div className="company-image-list">{settings.companyImages!.map((image,index)=><div key={`${image}-${index}`}><img src={image} alt={`公司照片 ${index+1}`}/><button onClick={()=>setSettings(value=>({...value,companyImages:value.companyImages?.filter((_,i)=>i!==index)}))}><Trash2/> 移除</button></div>)}</div>}<div className="admin-grid"><label>认证 / 执行标准（用 | 分隔）<input value={settings.certifications||""} onChange={event=>setSettings({...settings,certifications:event.target.value})} placeholder="ISO 9001|CE|RoHS（只填写真实拥有或适用的）" /></label><label>贸易条款<input value={settings.tradeTerms||""} onChange={event=>setSettings({...settings,tradeTerms:event.target.value})} placeholder="EXW / FOB / CIF, confirmed by quotation" /></label><label>付款方式说明<input value={settings.paymentTerms||""} onChange={event=>setSettings({...settings,paymentTerms:event.target.value})} placeholder="Confirmed according to order and buyer qualification" /></label><label>主要出口市场<input value={settings.exportMarkets||""} onChange={event=>setSettings({...settings,exportMarkets:event.target.value})} placeholder="Europe, North America, Southeast Asia..." /></label><label className="wide">质检流程（英文，用 | 分隔）<textarea value={settings.qualityProcess||""} onChange={event=>setSettings({...settings,qualityProcess:event.target.value})} placeholder="Requirement review|Pre-production sample|In-process check|Pre-shipment inspection" /></label></div><p className="settings-reminder">请只填写可以向客户证明的真实信息，修改后点击页面上方“保存设置”。</p></div>;
}
