"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Check, Mail, Menu, MessageCircle, PackageCheck, ShieldCheck, X } from "lucide-react";
import type { Product } from "@/lib/types";

export default function Storefront({ initialProducts }: { initialProducts: Product[] }) {
  const [menu, setMenu] = useState(false), [category, setCategory] = useState("All"), [selected, setSelected] = useState(""), [sent, setSent] = useState(false);
  const categories = ["All", ...Array.from(new Set(initialProducts.map(p => p.category)))];
  const products = useMemo(() => category === "All" ? initialProducts : initialProducts.filter(p => p.category === category), [category, initialProducts]);
  async function submit(formData: FormData) { const res = await fetch("/api/inquiries", { method: "POST", body: formData }); if (res.ok) setSent(true); }
  return <main>
    <header className="nav"><a className="brand" href="#top"><span>FN</span><b>FORGENOVA</b><small>HARDWARE</small></a><nav className={menu ? "open" : ""}><a href="#products">Products</a><a href="#capabilities">Capabilities</a><a href="#about">About</a><a href="#contact">Contact</a><a className="nav-quote" href="#quote">Request a Quote</a></nav><button className="menu" aria-label="Toggle navigation" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <section className="hero" id="top"><div className="hero-bg"/><div className="hero-copy"><div className="eyebrow">ENGINEERED FOR RELIABILITY</div><h1>Hardware that holds<br/><em>business together.</em></h1><p>Precision fasteners, fittings and custom metal components for distributors, builders and industrial buyers worldwide.</p><div className="hero-actions"><a className="primary" href="#products">Explore Products <ArrowRight/></a><a className="ghost" href="#quote">Get a Quote</a></div><div className="markets"><span>Supplying</span><b>North America</b><b>United Kingdom</b><b>Western Europe</b></div></div></section>
    <section className="trust"><div><PackageCheck/><b>Flexible MOQ</b><span>Built for growing orders</span></div><div><ShieldCheck/><b>Quality Assured</b><span>Inspection before shipment</span></div><div><MessageCircle/><b>Fast Response</b><span>Quotes within 24 hours</span></div></section>
    <section className="section" id="products"><div className="section-head"><div><span className="kicker">PRODUCT RANGE</span><h2>Built for demanding applications.</h2></div><p>Standard and custom components sourced with consistent specifications, competitive lead times and export-ready packaging.</p></div><div className="filters">{categories.map(c => <button key={c} className={category === c ? "active" : ""} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="products">{products.map((p, i) => <article className="product" key={p.id}><div className={`product-art art-${i % 4}`}><span>{String(i + 1).padStart(2,"0")}</span><div className="metal-shape"/></div><div className="product-body"><span className="product-category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><dl><div><dt>Material</dt><dd>{p.material}</dd></div><div><dt>MOQ</dt><dd>{p.moq}</dd></div></dl><div className="product-foot"><b>{p.price}</b><button onClick={() => { setSelected(p.name); document.querySelector("#quote")?.scrollIntoView({behavior:"smooth"}); }}>Quote <ArrowRight/></button></div></div></article>)}</div></section>
    <section className="capabilities" id="capabilities"><div><span className="kicker">FROM SPECIFICATION TO SHIPMENT</span><h2>A supply partner,<br/>not just a vendor.</h2><p>We coordinate sourcing, production, inspection and export packing so your team can buy with confidence.</p><a href="#quote">Discuss your requirements <ArrowRight/></a></div><ol><li><span>01</span><div><b>Specification review</b><p>Drawings, materials, finishes and target pricing checked before quotation.</p></div></li><li><span>02</span><div><b>Sample & production</b><p>Pre-production samples available for custom and high-volume orders.</p></div></li><li><span>03</span><div><b>Inspection & delivery</b><p>Clear quality records, export packaging and coordinated international shipping.</p></div></li></ol></section>
    <section className="about" id="about"><span className="kicker">FORGENOVA HARDWARE</span><h2>Industrial discipline.<br/>Personal service.</h2><p>We help overseas buyers source dependable hardware from China without the usual communication gaps. One point of contact, clear documentation and practical support from inquiry to delivery.</p><div className="stats"><div><b>24h</b><span>Typical quote response</span></div><div><b>100%</b><span>Pre-shipment inspection</span></div><div><b>OEM</b><span>Custom production support</span></div></div></section>
    <section className="quote" id="quote"><div className="quote-intro"><span className="kicker">START A CONVERSATION</span><h2>Tell us what<br/>you need.</h2><p>Share a part number, drawing or rough requirement. We’ll respond with the right questions and a practical quotation.</p><div className="contact-cards" id="contact"><a href="mailto:sales@example.com"><Mail/><span><small>Email</small>sales@example.com</span></a><a href="#quote"><MessageCircle/><span><small>WhatsApp</small>Number to be added</span></a></div></div>{sent ? <div className="success"><Check/><h3>Inquiry received.</h3><p>Thank you. Our team will respond within one business day.</p><button onClick={() => setSent(false)}>Send another inquiry</button></div> : <form action={submit}><div className="form-grid"><label>Full name<input name="name" required placeholder="Your name"/></label><label>Work email<input name="email" type="email" required placeholder="you@company.com"/></label><label>Company<input name="company" placeholder="Company name"/></label><label>Country / Region<input name="country" placeholder="United States"/></label><label>Product<select name="product" value={selected} onChange={e => setSelected(e.target.value)}><option value="">Select a product</option>{initialProducts.map(p => <option key={p.id}>{p.name}</option>)}</select></label><label>Estimated quantity<input name="quantity" placeholder="e.g. 5,000 pcs"/></label></div><label>Requirements<textarea name="message" required placeholder="Material, size, finish, standard, target quantity or other details..."/></label><button className="primary submit">Send Inquiry <ArrowRight/></button><small className="privacy">Your information is used only to respond to this inquiry.</small></form>}</section>
    <footer><a className="brand light" href="#top"><span>FN</span><b>FORGENOVA</b><small>HARDWARE</small></a><p>Precision hardware supply for global industry.</p><div><a href="#products">Products</a><a href="#quote">Request Quote</a><a href="/admin">Admin</a></div><small>© 2026 ForgeNova Hardware. All rights reserved.</small></footer>
  </main>;
}
