import { promises as fs } from "node:fs";
import path from "node:path";
import type { Inquiry, Product, SiteSettings } from "./types";

const defaults: Product[] = [
  { id: "kitchen-shears", name: "Heavy-Duty Kitchen Shears", category: "Kitchen Scissors", material: "3Cr14 / 420J2 Stainless Steel", blade: "Micro-serrated edge", size: "8–9 in", price: "Request quote", moq: "500 pcs", status: "Made to Order", description: "Multi-purpose kitchen shears for poultry, herbs and food preparation, available with bottle opener and nutcracker functions.", applications: "Kitchen retail, cookware brands, supermarket private label", features: "Micro-serrated blade|Comfort-grip handle|Dishwasher-safe options", customization: "Logo, handle color, retail card, gift box", leadTime: "25–35 days", image: "/scissors-catalog.png", imagePosition: "0% 0%" },
  { id: "tailor-scissors", name: "Professional Tailor Scissors", category: "Fabric Scissors", material: "High-Carbon Steel / Stainless Steel", blade: "Precision ground straight edge", size: "8–12 in", price: "Request quote", moq: "300 pcs", status: "Made to Order", description: "Smooth, controlled cutting for fabric, upholstery and craft use, with adjustable pivot and ergonomic handles.", applications: "Textile distributors, sewing brands, craft retailers", features: "Long-lasting sharpness|Adjustable pivot|Left-hand options", customization: "Blade finish, handle color, logo, packaging", leadTime: "25–40 days", image: "/scissors-catalog.png", imagePosition: "50% 0%" },
  { id: "pruning-shears", name: "Bypass Pruning Shears", category: "Garden Tools", material: "SK5 Carbon Steel", blade: "PTFE-coated bypass blade", size: "8 in", price: "Request quote", moq: "500 pcs", status: "Made to Order", description: "Clean-cut pruning shears for live stems and garden maintenance with a safety lock and replaceable spring options.", applications: "Garden centers, tool brands, home improvement retail", features: "SK5 hardened blade|One-hand safety lock|Non-slip grip", customization: "Handle color, blade coating, logo, blister pack", leadTime: "30–40 days", image: "/scissors-catalog.png", imagePosition: "100% 0%" },
  { id: "electrician-scissors", name: "Electrician Cable Scissors", category: "Professional Tools", material: "Stainless Steel", blade: "Serrated cable-cutting edge", size: "5.5–6.5 in", price: "Request quote", moq: "500 pcs", status: "Made to Order", description: "Compact professional scissors designed for cable, insulation and everyday electrical installation work.", applications: "Electrical wholesalers, tool kits, industrial supply", features: "Cable notch|Serrated edge|Impact-resistant handle", customization: "Handle color, laser logo, pouch, tool kit packing", leadTime: "25–35 days", image: "/scissors-catalog.png", imagePosition: "0% 100%" },
  { id: "aviation-snips", name: "Compound Aviation Tin Snips", category: "Professional Tools", material: "Chrome Molybdenum Steel", blade: "Serrated compound-action blade", size: "10 in", price: "Request quote", moq: "300 pcs", status: "Made to Order", description: "High-leverage snips for sheet metal, mesh and workshop applications, available in straight, left and right cut versions.", applications: "HVAC supply, hardware stores, industrial distributors", features: "Compound leverage|Color-coded grips|Safety latch", customization: "Grip color, logo, retail card, three-piece set", leadTime: "30–45 days", image: "/scissors-catalog.png", imagePosition: "50% 100%" },
  { id: "oem-scissor-set", name: "OEM Private Label Scissor Set", category: "OEM & Private Label", material: "Built to specification", blade: "Multiple blade options", size: "Custom assortment", price: "Request quote", moq: "500 sets", status: "Request Quote", description: "A configurable scissor program for brands and importers, covering product selection, logo, colors and retail-ready packaging.", applications: "Private labels, promotional programs, retail buyers", features: "Mixed product sets|Retail-ready packaging|Pre-shipment inspection", customization: "Full private label and packaging development", leadTime: "35–50 days", image: "/scissors-catalog.png", imagePosition: "100% 100%" },
];
const defaultSettings: SiteSettings = { companyName: "ForgeNova Cutting Tools", email: "sales@example.com", whatsapp: "Number to be added", wechat: "ID to be added", tagline: "Scissors engineered for your market.", instagram: "", facebook: "", tiktok: "", about: "We help overseas distributors and brands source dependable scissors and cutting tools from China. One point of contact for product matching, private label packaging, quality inspection and export delivery." };
type Data = { products: Product[]; inquiries: Inquiry[]; settings: SiteSettings };
const dataDir = process.env.DATA_DIR || path.join(process.cwd(), "data");
const dataFile = path.join(dataDir, "store.json");
async function read(): Promise<Data> { try { const data = JSON.parse(await fs.readFile(dataFile, "utf8")); const source:Product[] = Array.isArray(data.products) ? data.products : defaults; const products = source.map((product:Product) => ({ ...product, image: product.image || defaults.find(item => item.id === product.id)?.image })); return { products, inquiries: data.inquiries || [], settings: { ...defaultSettings, ...(data.settings || {}) } }; } catch { const initial = { products: defaults, inquiries: [], settings: defaultSettings }; await fs.mkdir(dataDir, { recursive: true }); await fs.writeFile(dataFile, JSON.stringify(initial, null, 2)); return initial; } }
async function write(data: Data) { await fs.mkdir(dataDir, { recursive: true }); const temp = `${dataFile}.tmp`; await fs.writeFile(temp, JSON.stringify(data, null, 2)); await fs.rename(temp, dataFile); }
export async function getProducts() { return (await read()).products; }
export async function getProduct(id: string) { return (await read()).products.find(product => product.id === id); }
export async function getInquiries() { return (await read()).inquiries; }
export async function getSettings() { return (await read()).settings; }
export async function saveProducts(products: Product[]) { const data = await read(); data.products = products; await write(data); }
export async function saveSettings(settings: SiteSettings) { const data = await read(); data.settings = settings; await write(data); }
export async function addInquiry(inquiry: Inquiry) { const data = await read(); data.inquiries.unshift(inquiry); await write(data); }
