export type Product = {
  id: string;
  name: string;
  category: string;
  material: string;
  price: string;
  moq: string;
  status: "In Stock" | "Made to Order" | "Request Quote";
  description: string;
  image?: string;
  images?: string[];
  imagePosition?: string;
  blade?: string;
  size?: string;
  applications?: string;
  features?: string;
  customization?: string;
  leadTime?: string;
  sku?: string;
  active?: boolean;
  featured?: boolean;
  model?: string;
  packaging?: string;
  certification?: string;
  specifications?: string;
  videoUrl?: string;
};

export type Inquiry = {
  id: string;
  name: string;
  email: string;
  company: string;
  country: string;
  product: string;
  quantity: string;
  requestType?: string;
  message: string;
  source?: string;
  landingPage?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  createdAt: string;
  stage?: string;
  notes?: string;
  followUp?: string;
  attachmentUrl?: string;
  attachmentName?: string;
};

export type SiteSettings = {
  companyName: string;
  email: string;
  whatsapp: string;
  wechat: string;
  about: string;
  tagline?: string;
  instagram?: string;
  facebook?: string;
  tiktok?: string;
  googleAnalyticsId?: string;
  metaPixelId?: string;
  tiktokPixelId?: string;
  logo?: string;
  legalName?: string;
  address?: string;
  businessHours?: string;
};
